### ISSUE TITLE
tests in the shared module

### ISSUE THREAD

**Issue by fommil** [scala-js/scalajs-cross-compile-example#4]
it would be good to have some utests in the shared module (or scalatests that are caveated to only run under the JVM)

**Comment by sjrd** [comment]
I suppose I could create a branch with uTests tests, yes. I'll do that once 0.6.0 final is out.

**Comment by fommil** [comment]
I am getting some traction turning my simple project into a shared/jvm/js with utest support. Keep an eye on the kerbal-calculator project over the next few hours. I'll try to do all conversions to scalajs under one commit.
