### ISSUE TITLE
CrossProject does not copy conf folder.

### ISSUE THREAD

**Issue by dsarosi** [scala-js/scalajs-cross-compile-example#6]
I tried to add scala-i18n to a CrossProject which requires resource files inside a conf folder.  Such files are not copied to their respective .js and .jvm folders.

**Comment by er1c** [comment]
I'm trying to wrap my head around this same issue, is it still an unsolved issue?

**Comment by sjrd** [comment]
I'm closing all the issues in this repo. Issues about cross projects should go to https://github.com/portable-scala/sbt-crossproject, and questions should be asked on StackOverflow or Gitter.
