### ISSUE TITLE
Problem enabling plugins for submodule?

### ISSUE THREAD

**Issue by bbarker** [scala-js/scalajs-cross-compile-example#9]
See full info at:

http://stackoverflow.com/questions/39919301/how-to-enableplugins-for-subprojects-when-using-scala-js-crosscompile

Not sure if this is really an issue or just my fumbling with SBT.

My failing changes [are on github](https://github.com/bbarker/scalajs-cross-compile-example/commit/213c304e801f72d4f5442083f2527daf7f491da7).

**Comment by gzm0** [comment]
I have answered your SO question.
